name: "amml_python_ml_template"
services:
  # Note: If desired, add "version: slim" to the build args
  # Warn: We cannot set the Docker container to work in the
  # `host` mode, as it interferes with PyCharm handling of
  # how Jupyter is run. However, we can make an alias for
  # the host network accessible to the Docker container.
  amml-project-cpu:
    build:
      context: .
      args:
        hardware: cpu
    env_file: ".env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: bash
    volumes:
      - .:/opt/project
    image: amml-project-cpu:latest
  amml-project-hydra-cpu:
    build:
      context: .
      args:
        hardware: cpu
    env_file: ".env"
    extra_hosts:
      - "host.docker.internal:10.18.74.13"
    command: bash
    volumes:
      - .:/opt/project
    image: amml-project-cpu:latest
  amml-project-cuda:
    build:
      context: .
      args:
        hardware: cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    env_file: ".env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: bash
    volumes:
      - .:/opt/project
    image: amml-project-cuda:latest
  amml-project-hydra-cuda:
    build:
      context: .
      args:
        hardware: cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    env_file: ".env"
    extra_hosts:
      - "host.docker.internal:10.18.74.13"
    command: bash
    volumes:
      - .:/opt/project
    image: amml-project-cuda:latest